# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{trash}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lee Jones"]
  s.date = %q{2010-03-26}
  s.default_executable = %q{trash}
  s.description = %q{when its hard to say goodbye, and rm is just too much... use trash instead.}
  s.email = %q{scribblethink@gmail.com}
  s.executables = ["trash"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/trash",
     "config/cucumber.yml",
     "features/step_definitions/trash_steps.rb",
     "features/support/env.rb",
     "features/trash.feature",
     "lib/trash.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/trash_spec.rb",
     "trash.gemspec"
  ]
  s.homepage = %q{http://github.com/leejones/trash}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{trash can for the command line}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/trash_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

