# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: trash 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "trash".freeze
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Lee Jones".freeze]
  s.date = "2017-01-24"
  s.description = "when it's hard to say goodbye, and rm is just too much... use trash instead.".freeze
  s.email = "scribblethink@gmail.com".freeze
  s.executables = ["trash".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/trash",
    "lib/trash.rb",
    "spec/spec_helper.rb",
    "spec/trash_spec.rb",
    "trash.gemspec"
  ]
  s.homepage = "http://github.com/leejones/trash".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "trash can for the command line".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.14.1"])
      s.add_development_dependency(%q<rake>.freeze, ["~> 10.1.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.0.1"])
    else
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.14.1"])
      s.add_dependency(%q<rake>.freeze, ["~> 10.1.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 4.0.1"])
    end
  else
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.14.1"])
    s.add_dependency(%q<rake>.freeze, ["~> 10.1.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.0.1"])
  end
end

